services:
  envoy:
    image: istio/proxyv2:1.24.2
    entrypoint:
      - /usr/local/bin/envoy
      - --log-level warn
      - -c
      - /etc/envoy/envoy.yml
    ports:
      - 10000:10000 # envoy: proxy
      - 15000:15000 # envoy: admin
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yml

  extproc-go:
    build:
      context: ../
      dockerfile: examples/Dockerfile
    hostname: host.testcontainers.internal
    ports:
      - 8080:8080 # extproc: http echo
      - 8081:8081 # extproc: grpc server
    develop:
      watch:
        - action: rebuild
          path: "../"
          ignore:
            - "**/*_test.go"
            - "**/*.yml"
            - "**/*.yaml"
    healthcheck:
      test: ["CMD", "./healthcheck", "--url", "http://extproc-go:8080/headers", "--timeout", "10s"]
      interval: 5s
      timeout: 10s
      retries: 60
